services:
  web:
    image: event-backend:latest
    container_name: django_web_blue
    restart: always

    ports:
      - "8000:8000"
    depends_on:
      - redis_blue

  celery:
    image: event-backend:latest
    container_name: celery_blue
    restart: always
    command: celery -A config worker --loglevel=info

    depends_on:
      - redis_blue

  redis:
    image: redis:7-alpine
    container_name: redis_blue
    restart: always