
services:
  web:
    image: event-backend:latest
    container_name: django_web_green
    restart: always

    ports:
      - "8001:8000"
    depends_on:
      - redis_green

  celery:
    image: event-backend:latest
    container_name: celery_green
    restart: always
    command: celery -A config worker --loglevel=info

    depends_on:
      - redis_green

  redis:
    image: redis:7-alpine
    container_name: redis_green
    restart: always